# Generated by Django 4.2.25 on 2025-11-17 04:03

from django.db import migrations, models
import ft.tagging


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0006_section_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacecanvas',
            name='tags',
            field=models.JSONField(blank=True, default=ft.tagging.generate_placeholder_tags),
        ),
    ]
