# Generated by Django 4.2.26 on 2026-03-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0008_workspacesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='current_period_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='last_event_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='provider_customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='provider_order_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='provider_product_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='provider_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='provider_subscription_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='provider_test_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='provider_variant_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='workspacesubscription',
            index=models.Index(fields=['provider_subscription_id'], name='ft_workspac_provide_badf7f_idx'),
        ),
    ]
